---
title: "Wild data"
author: "Atahualpa"
format: html
editor: visual
execute: 
  error: false
  warning: false
---
```{r}
library(janitor)
library(tidyverse)
library(here)
library(dplyr)



```
### Read in the data

```{r}
mark_verts <- read.csv(here("data", "AS00601.csv"))
glimpse(mack_verts)

```

### A bit of wrangling $ exploring

```{r}
mc_wt_5 <- mark_verts$WEIGHT[5]
mc_wt_5

mc_length_8_20 <- mark_verts$LENGTH1[8:20]
mc_length_8_20

mc_dates <- mark_verts$SAMPLEDATE
mc_dates
```
### make a salamander subset
```{r}
mc_salamaders <- filter(mark_verts, SPECIES == "DITE" )
mc_salamaders

```

### Make a scatterplot of salamander length x weight

```{r}
```


```{r}
salamander_plot <- ggplot(mc_salamaders, aes(x=LENGTH1, y=WEIGHT))+
  geom_point(shape=18, color="green", )+
  geom_smooth(linetype="dashed")+
  labs(title="Pacific Giant Salamanders length x weight ",
       subtitle = "species: Dicamptodon tenebrosus", 
       x="weigth (gr)",
       y="length (mm)",
       caption ="Source: Gregory, S.V. and I. Arismendi, 2020")
salamander_plot

salamander_size <- ggsave( "salamander_size.jpg" , plot= salamander_plot, dpi = 300)
```
### Make a cutthroat plot

```{r}
mc_salamaders_oncl <- filter(mark_verts, SPECIES == "ONCL" )
mc_salamaders_oncl

salamander_plot_oncl <- ggplot(mc_salamaders_oncl, aes(x=LENGTH1, y=WEIGHT, color=REACH))+
  geom_point(shape=10 )+
  geom_smooth(linetype="dashed")+
  labs(title="ONCL Salamanders length x weight ",
       subtitle = "species: ONCL", 
       x="weigth (gr)",
       y="length (mm)",
       caption ="Source: Gregory, S.V. and I. Arismendi, 2020")
salamander_plot_oncl

cutthroat_size <- ggsave( "cutthroat_size.jpg" , plot= salamander_plot, dpi = 300)
```


